---
- name: WP Blog Setup 
  hosts: blog
  become: true
  vars:
    appname: blog 
  vars_files:
    - "{{ env }}/group_vars/blog"
  roles:
    - ulimit
    - timezone
    - docker
    - docker-compose 
