- name: Ensure the Droplet is exist
  digital_ocean:
    state: present
    command: droplet
    id: {{ droplet_id }}
    name: {{ droplet_name }}
    api_token: {{ digitalocean_token }}
    size_id: {{ droplet_size }}
    region_id: sgp1
    image_id: ubuntu-14-04-x64
    wait_timeout: 500
  tags: [get_facts]
